version: 2 
 updates: 
 - package-ecosystem: "bundler"
   directory: "/" 
   schedule: 
     interval: "daily"
     time: "22:30"
 - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:30"



     
