name: Le 7eptième Œil
title: Le 7eptième Œil | L'œil qui voit tout le Cinéma
description: >- # this means to ignore newlines until "baseurl:"
  L'œil qui voit tout le Cinéma
tags:
  - blog
  - cinema
  - critique
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: A Propos
    url: /about
  - title: Nous contacter
    url: /contact
  - title: Feed
    url: /feed.xml
email: le7eptiemeoeil@gmail.com

# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mqknkwel
# Localization
date_format: "%d %B %Y"
language: "fr"