name: Plume Quantique
title: Plume Quantique | Blog consacré à la science-fiction
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenue dans mon esprit, où se mèlent science-fiction, cinéma, littérature avec passion.
tags:
  - blog
  - science-fiction
  - cinema
  - critique
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: A Propos
    url: /about
  - title: Me contacter
    url: /contact
  - title: Feed
    url: /feed.xml
email: amlamanangekevin@gmail.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mqknkwel
# Localization
date_format: "%d %B %Y"
language: "fr"